### ISSUE TITLE
feat: a single command to run nodes and other commands on the same terminal

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelar-examples#125]
Is it possible to run both nodes and project simultaneously with a single command instead of opening two separate terminals?

**Comment by StephenFluin** [comment]
It would be possible, but the outputs would be mixed, creating a very confusing UX, what are you hoping to see?

**Comment by Olanetsoft** [comment]
> It would be possible, but the outputs would be mixed, creating a very confusing UX; what are you hoping to see?

I understand now. Initially, I thought it would be best to run it on the same terminal to prevent errors. However, I recall that we included a guide in the readme instructing users to run the node on a separate terminal before testing. 

Additionally, you're right about the potential confusion with the UX when testing on the terminal.

Closing this!
