### ISSUE TITLE
feat: remove hard dependencies on non-evm chain stacks

### ISSUE THREAD

**Issue by StephenFluin** [axelarnetwork/axelar-examples#127]
Right now when cloning and installing dependencies for this repo, we require all of the dependnecies of every chain stack we support (near, aptos, and more in the future).

This means that our repo is harder to install and maintain (windows support for example). We should design a new architecture that makes some of these optional dependencies, or not included at all, and then automatically add the additional dependencies based on the chain stacks a user wants to develop for.

**Comment by Olanetsoft** [comment]
@npty, when are we looking to close this? There have been even more complaints from developers using Windows, and they don't even want to do anything with NEAR yet, but they are stuck.

**Comment by npty** [comment]
> @npty, when are we looking to close this? There have been even more complaints from developers using Windows, and they don't even want to do anything with NEAR yet, but they are stuck.

sorry for the delay, i'll look at this tomorrow.
