### ISSUE TITLE
npm run check-balance local doesn't work

### ISSUE THREAD

**Issue by devguru84** [axelarnetwork/axelar-examples#172]
I followed all the steps.
I run the local chain using `npm run start` and it says 'Serving 5 networks on port 8500'.
But when I am going to run `npm run check-balance local` it says 'could not detect network'.
Same error occurs when I try on examples-web sample.

**Comment by Olanetsoft** [comment]
@devguru84  When you run the command: 

```
npm run start
```

You should leave this node running on a separate terminal before deploying and testing. Then, run `npm run check-balance local` on another terminal.

**Comment by devguru84** [comment]
@Olanetsoft, I did it correctly.

`npm run start` on one terminal and `npm run check-balance local` on another terminal.
But the error occurs when it is going to connect the RPC.(http://localhost:8500/1)

**Comment by devguru84** [comment]
![Screenshot_4](https://github.com/axelarnetwork/axelar-examples/assets/162280013/73c0b93d-ff3f-4560-a57c-7b3cee61926f)
And I found that this code doesn't work correctly.
It displays nothing on current code and I found it couldn't retrieve chains correctly and  I changed that part.
Not sure, how it works on others.

**Comment by devguru84** [comment]
I fixed the issue, @Olanetsoft 
Thanks for your help.
There was a problem with my network configuration.
I can see the balances now.
Thanks.

**Comment by aChaoLuo** [comment]
> I fixed the issue, [@Olanetsoft](https://github.com/Olanetsoft) Thanks for your help. There was a problem with my network configuration. I can see the balances now. Thanks.
hello, i have a same problem. Could you tell me your answer to this  problem.😊
